config/routes.rb
Rails.application.routes.draw do
  resource :update_harvest_data, only: :create, controller: "update_harvest_data"
  resources :tags, only: [:index, :show, :edit, :update]
  root 'tags#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job_status.rb
class JobStatus < ApplicationRecord
  def self.get
    all.first_or_create!
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_time_entries, dependent: :destroy
  has_many :time_entries, through: :tag_time_entries

  scope :budgeted, -> { where.not(budget: nil) }
  scope :unbudgeted, -> { where(budget: nil) }

  after_update_commit { broadcast_replace_to "tags" }

  validates :budget, presence: true, on: :update

  def hours_spent
    time_entries.sum(:hours).round(1)
  end
end

app/models/tag_time_entry.rb
class TagTimeEntry < ApplicationRecord
  belongs_to :tag
  belongs_to :time_entry
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  has_many :tag_time_entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end

  def show
    @tag = Tag.find params[:id]
    render @tag
  end

  def edit
    @tag = Tag.find params[:id]
  end

  def update
    @tag = Tag.find params[:id]
    if @tag.update params.require(:tag).permit(:budget)
      redirect_to @tag
    else
      render :edit
    end
  end
    
end

app/controllers/update_harvest_data_controller.rb
class UpdateHarvestDataController < ApplicationController
  def create
    JobStatus.get.update state: "queued"
    LoadHarvestDataJob.perform_later
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/update_harvest_data_helper.rb
module UpdateHarvestDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>4gr8justis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

  <body>
    <div class="container px-8 pb-8">
      <header class="flex mb-8 items-center">
        <h1 class="text-6xl">4gr8justis</h1>
        <%= image_pack_tag "you_have_no_chance.png", class: "ml-auto" %>
      </header>
      <%= yield %>

    </div>
    
  </body>
</html>

app/views/tags/_tag.html.erb
<%- 
  color = tag.budget ? "orange" : "green"
  color_class = "bg-#{color}-300"
%>

<%= turbo_frame_tag dom_id(tag) do %>
  <div class="block mb-2">
    <%= link_to edit_tag_path(tag), class: "inline-block w-24" do %>
      <div class="c-tag <%= color_class %>">
         #<%= tag.name %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" height="20" width="20" class="c-tag__edit">
          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
        </svg>
      </div>
    <% end -%>

    <%= tag.hours_spent %>
    <%- if tag.budget %>
      / <%= tag.budget.round(1) %>
    <%- end %>
  </div>
  
<%- end %>

app/views/tags/_tags.html.erb
<%= turbo_frame_tag "tags" do %>
  <div class="mb-6">
    <h2 class="mb-2">Budgeted Tags</h2>
    <%= render Tag.budgeted %>
  </div>

  <div class="mb-6">
    <h2 class="mb-2">Unbudgeted Tags</h2>
    <%= render Tag.unbudgeted %>
  </div>

  <div class="mt-6">
    Data Updated: <%= JobStatus.get.updated_at.strftime("%A %B %-d, %Y %-l:%M %p") %>
    <br>
    Job Status: <%= JobStatus.get.state.humanize.titleize %>

    <%- if JobStatus.get.state == "running" %>
      <%= image_pack_tag "ajax-loader.gif", class: "inline-block ml-2" %>
    <%- else %>
      <%=
        button_to "Update Data from Harvest",
          update_harvest_data_path,
          class: "px-5 py-3 mt-3 bg-orange-300 rounded"
      %>
    <%- end %>
  </div>
<%- end %>

app/views/tags/edit.html.erb
<%- 
  color = tag.budget ? "orange" : "green"
  color_class = "bg-#{color}-300"
  tag = @tag
  input_class = "border rounded w-1/4"
  input_class << " border-red-600" if tag.errors.include?(:budget)
%>

<%= turbo_frame_tag dom_id(tag) do %>
  <div class="block mb-2">
    <%= link_to edit_tag_path(tag), class: "inline-block w-24" do %>
      <div class="c-tag <%= color_class %>">
         #<%= tag.name %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" height="20" width="20" class="c-tag__edit">
          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
        </svg>
      </div>
    <% end -%>

    <%= tag.hours_spent %>
    /
    <%= form_with model: tag, class: "inline-flex" do |f| %>
      <%= f.number_field :budget, class: input_class, autofocus: true %>
      <%= f.submit "Save", class: "ml-2 rounded px-2 bg-purple-300" %>
      <%= link_to "Cancel", tag, class: "ml-2 rounded px-2 bg-gray-300" %>
      <i class="text-sm ml-2 text-red-600"><%= tag.errors.full_messages_for(:budget).join %></i>
      
    <%- end %>
  </div>
  
<%- end %>

app/views/tags/index.html.erb
<%= turbo_stream_from "tags" %>

<%= render 'tags' %>